version: '3'
services:
  db:
    image: postgres:10.4-alpine
    volumes:
      - /var/lib/postgresql/data
    networks:
     - db
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    # command: tail -f /dev/null
    volumes:
     - ./src:/app
    ports:
     - "3000:3000"
    depends_on:
     - db
    networks:
     - db
    tty: true
    stdin_open: true

networks:
  db: